# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d81269bb1b28646b94a4e4b30fdb2ba8ab6f36fcda331cef1bf10bed1707edf217c89980e1498f1ad24096f18bcc472d60b04b000883fbfbcd51dade9617274

test:
  secret_key_base: 6e82b31819db6b052ec16be71f5bda41050895f36743dd963494ad73b6783c174dba9d073bb65f35eed2b69efef3e942c0fba842507331a82ef869cf72bed749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
